-
  name: 'Add item to cart'
  uriPattern: 'cart/item/add'
  defaults:
    '@controller': 'Cart'
    '@package': 'NeosRulez.Neos.Cart'
    '@action': 'addItem'
    '@format': 'json'
-
  name: 'Update item in cart'
  uriPattern: 'cart/item/update'
  defaults:
    '@controller': 'Cart'
    '@package': 'NeosRulez.Neos.Cart'
    '@action': 'updateItem'
    '@format': 'json'
-
  name: 'Remove item from cart'
  uriPattern: 'cart/item/delete'
  defaults:
    '@controller': 'Cart'
    '@package': 'NeosRulez.Neos.Cart'
    '@action': 'deleteItem'
    '@format': 'json'
-
  name: 'Flush cart'
  uriPattern: 'cart/flush'
  defaults:
    '@controller': 'Cart'
    '@package': 'NeosRulez.Neos.Cart'
    '@action': 'flush'
    '@format': 'json'
-
  name: 'Add shipping to cart'
  uriPattern: 'cart/shipping/add'
  defaults:
    '@controller': 'Cart'
    '@package': 'NeosRulez.Neos.Cart'
    '@action': 'addShipping'
    '@format': 'json'

-
  name: 'Get items from cart'
  uriPattern: 'cart/items'
  defaults:
    '@controller': 'Cart'
    '@package': 'NeosRulez.Neos.Cart'
    '@action': 'items'
    '@format': 'json'
-
  name: 'Get summary'
  uriPattern: 'cart/summary'
  defaults:
    '@controller': 'Cart'
    '@package': 'NeosRulez.Neos.Cart'
    '@action': 'summary'
    '@format': 'json'
